### PR TITLE
Fix files format

### LINKED ISSUE #1: Fix files format to match the pre-commit requisites
### Description

The current file format doesn't match the pre-commit requisites.

### Reproduction steps

```bash
running `pre-commit run -a` before commit will show the files with problems
```

### Logs

_No response_

### OS

_No response_

### PR DESCRIPTION
**Pull request by datejada**
# Pull request details

## Describe the changes made in this pull request

Fixing files format according to the pre-commit hooks

## List of related issues or pull requests

Closes #1

## Collaboration confirmation

As a contributor I confirm

- [x] I read and followed the instructions in README.dev.md
- [NA] The documentation is up to date with the changes introduced in this Pull Request (or NA)
- [NA] Tests are passing
- [ ] Lint is passing

### CODE REVIEW

**Comment by datejada** [comment]
@abelsiqueira This is the new repo for the fitting profile package. I'm still having a problem with the pre-commit and the prettier hook. Any ideas on how to solve it? Thanks!

**Comment by datejada** [comment]
@abelsiqueira would you mind double-checking that all is in place for this package? I think after fixing the formats, the basic set up is there, but just to double-check. Thanks!

File: src/model.jl [hunk 1]
```diff
@@ -20,7 +18,11 @@ function fit_profile(profile_values::Vector{Float64},
     @variable(model, x >= 0)
 
     # Create the objective function
-    @NLobjective(model, Min, (sum((profile_values[i])^x for i in 1:total_hours) - target_mean*total_hours)^2)
+    @NLobjective(
+        model,
+        Min,
+        (sum((profile_values[i])^x for i = 1:total_hours) - target_mean * total_hours)^2
```
Comment (abelsiqueira) [inline src/model.jl:24]: It would be useful to write the math for this in the docs. Something like

```math
\min \qquad \bigg(\mu h - \sum_{i = 1}^h p_i^x\bigg)^2
```

It would also make it easier to read with less parenthesis, that's why I moved things around.
I had the impression the problem was

```math
\min \qquad \sum_{i=1}^h (\mu - p_i^x)^2,
```

i.e., you want each `p_i^x` to be close to `\mu`.

**Review by abelsiqueira — APPROVED** [review]
Looks right to me. I made a small comment on the equation, but that is a separate issue.

File: src/model.jl (hunk 1 above)
Comment (abelsiqueira) [reply src/model.jl:24]: Never mind my comment, I read that you are just worried about the mean of the new `p_i^x`, not the individual `p_i^x` value, so the first definition is correct. I would maybe write as

```math
\min \qquad \frac{1}{2}\bigg(\mu - \frac{1}{h}\sum_{i=1}^h p_i^x\bigg)^2
```

Comment (abelsiqueira) [reply src/model.jl:24]: I realized something about the problem. You are doing nonlinear least squares of a single variable with a single equation. So it makes sense to ask whether the equation already has a solution. Under conditions on the profile values and the target_mean, it has, and in that case it would be simpler to use a root-finding algorithm.
For instance:

```julia
using Roots
profile_values = [0.2, 0.5, 0.9, 1.0, 0.4, 0.1, 0.0] 
target_mean = 0.5
find_zero(
	x -> sum(profile_values .^ x .- target_mean),
	[1e-2, 1.0],
)
```

Depending on what you want, and the assumptions that you can make, this can be used.
